In [3]:
import torch

In [4]:
X = torch.tensor([[0,0],[1,0],[0,1],[1,1]],dtype = torch.float32)
X

tensor([[0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 1.]])

<li> 实例化nn.Linear类<br>
    不需要定义 w 和 b 因为nn.module 子类在实例化时自动随机生成 w 和 b 。

In [5]:
# 人为设置随机数种子 仅在一个cell中生效
torch.random.manual_seed(10)
# 实例化nn.Linear类
output = torch.nn.Linear(2,1,bias = True)
# 第一个参数：上一层的神经元个数 (上一层的神经元中，给现在这一层传输数据的神经元的个数)
# 第二个参数：这一层的神经元个数 (接收传输数据的神经元的个数)

nn.module 子类在实例化时自动生成 w 和 b 。

In [6]:
output.weight

Parameter containing:
tensor([[-0.0593, -0.0242]], requires_grad=True)

In [7]:
output.bias

Parameter containing:
tensor([-0.2652], requires_grad=True)

<li>调用实例化类

In [8]:
zhat = output(X)
zhat

tensor([[-0.2652],
        [-0.3244],
        [-0.2894],
        [-0.3487]], grad_fn=<AddmmBackward0>)

In [9]:
z = torch.tensor([-0.2,-0.05,-0.05,0.1],dtype = torch.float32).reshape(4,1)
z

tensor([[-0.2000],
        [-0.0500],
        [-0.0500],
        [ 0.1000]])