In [18]:
import torch
from torch.nn import functional as F

<li>sigmoid函数

In [19]:
X = torch.tensor([[0,0],[1,0],[0,1],[1,1]],dtype = torch.float32)
X

tensor([[0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 1.]])

In [20]:
# 设置随机数种子 仅在一个cell中生效
torch.random.manual_seed(10)
# 实例化torch.nn.Linear
dense = torch.nn.Linear(2,1)
zhat = dense(X)
sigma = F.sigmoid(zhat)
y = [int(x) for x in sigma >= 0.5]

In [21]:
dense.bias

Parameter containing:
tensor([-0.2652], requires_grad=True)

In [22]:
y

[0, 0, 0, 0]

In [23]:
zhat

tensor([[-0.2652],
        [-0.3244],
        [-0.2894],
        [-0.3487]], grad_fn=<AddmmBackward0>)

<li> 符号函数、阶跃函数sign

In [14]:
torch.sign(zhat)

tensor([[-1.],
        [-1.],
        [-1.],
        [-1.]], grad_fn=<SignBackward0>)

<li>流线型单元函数ReLU

In [26]:
F.relu(zhat)

tensor([[0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)

<li> 双曲正切函数tanh

In [24]:
torch.tanh(zhat)

tensor([[-0.2591],
        [-0.3135],
        [-0.2816],
        [-0.3352]], grad_fn=<TanhBackward0>)