In [1]:
import torch
import numpy as np

# 张量的符号索引

## 一维张量索引

In [2]:
t1 = torch.arange(1,11)
t1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 从左到右， 从0开始
# 索引出来的是0维张量
t1[0]

tensor(1)

In [4]:
# 用法与python一样
t1[1:8:2]

tensor([2, 4, 6, 8])

In [5]:
# 区别在于 pytorch中不支持 step < 0 
t1[9:1:-1]

ValueError: step must be greater than zero

## 二维张量索引 

In [8]:
t2 = torch.arange(1,10).reshape(3,3)
t2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# 表示索引第一行、第二个 (第二列的)元素
t2[0,1]

tensor(2)

In [10]:
#表示索引第一行、步长为2
t2[0,::2]

tensor([1, 3])

In [11]:
# 索引结果同上
t2[0,[0,2]]

tensor([1, 3])

## 三维张量的索引

In [12]:
t3 = torch.arange(1,28).reshape(3,3,3)
t3

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [13]:
#索引第二个矩阵中，第二行、第二个元素
t3[1,1,1]

tensor(14)

In [14]:
# 索引第二个矩阵，行和列都是步长为2
t3[1,::2,::2]

tensor([[10, 12],
        [16, 18]])

In [15]:
t3.shape

torch.Size([3, 3, 3])

In [16]:
t3[1,1,1]

tensor(14)

# 张量的函数索引 

In [17]:
t1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
t1.ndim

1

In [19]:
indices = torch.tensor([1,2])
indices

tensor([1, 2])

In [20]:
torch.index_select(t1,0,indices)

tensor([2, 3])

在index_select函数中，第二个参数实际上代表的是索引的维度。对于t1这个一维向量来说，由于只有一个维度，因此第二个参数取值为0，就代表在第一个维度上进行索引

In [21]:
t2 = torch.arange(12).reshape(4,3)
t2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [22]:
t2.shape

torch.Size([4, 3])

In [23]:
indices

tensor([1, 2])

In [24]:
torch.index_select(t2,0,indices)

tensor([[3, 4, 5],
        [6, 7, 8]])

In [25]:
torch.index_select(t2,1,indices)

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])

# tensor.view()方法 

In [26]:
t = torch.arange(6).reshape(2,3)
t

tensor([[0, 1, 2],
        [3, 4, 5]])

In [27]:
te = t.view(3,2)
te

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [28]:
t

tensor([[0, 1, 2],
        [3, 4, 5]])

In [29]:
# 对t进行修改
t[0] = 1

In [30]:
t

tensor([[1, 1, 1],
        [3, 4, 5]])

In [31]:
# te也会发生变化
te

tensor([[1, 1],
        [1, 3],
        [4, 5]])

#  张量的分片函数

## 分块：chunk函数

chunk函数能够按照某维度，对张量进行均匀切分，并且返回结果是原张量的视图。

In [32]:
t2 = torch.arange(12).reshape(4,3)
t2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [33]:
tc = torch.chunk(t2,4,dim = 0)
tc

(tensor([[0, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[6, 7, 8]]),
 tensor([[ 9, 10, 11]]))

In [34]:
tc[0]

tensor([[0, 1, 2]])

In [35]:
tc[0][0]

tensor([0, 1, 2])

In [36]:
tc[0][0][0] = 1
tc

(tensor([[1, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[6, 7, 8]]),
 tensor([[ 9, 10, 11]]))

In [37]:
t2

tensor([[ 1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

注意:chunk返回结果是一个视图，不是新生成了一个对象

## 拆分：split函数 

split既能进行均分，也能进行自定义切分。当然，需要注意的是，和chunk函数一样，split返回结果也是view。

In [38]:
t2 = torch.arange(12).reshape(4,3)
t2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [39]:
# 第二个参数只输入一个数值时表示均分，第三个参数表示在哪一个维度上进行分割
torch.split(t2,2,0)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[ 6,  7,  8],
         [ 9, 10, 11]]))

In [40]:
# 第二个参数输入一个序列时，表示按照序列数值分
torch.split(t2,[1,3],0)

(tensor([[0, 1, 2]]),
 tensor([[ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]))

In [41]:
torch.split(t2,[1,2],1)

(tensor([[0],
         [3],
         [6],
         [9]]),
 tensor([[ 1,  2],
         [ 4,  5],
         [ 7,  8],
         [10, 11]]))

# 张量的合并操作 

张量的合并操作类似与列表的追加元素，可以拼接、也可以堆叠

## 拼接函数：cat 可以使用cat函数实现张量的拼接

In [42]:
a = torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [47]:
b = torch.ones(2,3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [48]:
c = torch.zeros(3,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [52]:
torch.cat([a,b]) #按照行进行拼接，dim默认取值为9

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [51]:
torch.cat([a,b],1) #按照列进行拼接

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [50]:
torch.cat([a,c],1) #形状不匹配时将报错

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 3 for tensor number 1 in the list.

## 堆叠函数：stack 和拼接不同，堆叠不是将元素拆分重装，而是简单的将各参与堆叠的对象分装到一个更高维度的张量里。 

In [53]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [54]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [56]:
torch.stack([a,b])

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [57]:
torch.stack([a,b]).shape

torch.Size([2, 2, 3])

In [58]:
torch.cat([a,b])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

注意对比二者区别，拼接之后维度不变，堆叠之后维度升高。拼接是把一个个元素单独提取出来之后再放到二维张量中，而堆叠则是直接将两个二维张量封装到一个三维张量中，因此，堆叠的要求更高，参与堆叠的张量必须形状完全相同。

# 张量维度变换 

## squeeze函数：删除不必要的维度 

In [59]:
t = torch.zeros(1,1,3,1)
t

tensor([[[[0.],
          [0.],
          [0.]]]])

In [60]:
# t张量解释:一个包含一个三维的四维张量，三维张量只包含一个三行一列的二维张量
t.shape

torch.Size([1, 1, 3, 1])

In [61]:
torch.squeeze(t)

tensor([0., 0., 0.])

In [64]:
torch.squeeze(t).shape

torch.Size([3])

In [66]:
t1 = torch.zeros(1,1,3,2,1,2)
t1.shape

torch.Size([1, 1, 3, 2, 1, 2])

In [67]:
print(torch.squeeze(t1))
print(torch.squeeze(t1).shape)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([3, 2, 2])


简单理解，squeeze就相当于提出了shape返回结果中的1

## unsqueeze函数：手动升维

In [68]:
t = torch.zeros(1,2,1,2)
t.shape

torch.Size([1, 2, 1, 2])

In [71]:
torch.unsqueeze(t,dim = 0)  # 在第1个维度索引上升1 个维度

tensor([[[[[0., 0.]],

          [[0., 0.]]]]])

In [72]:
torch.unsqueeze(t,dim = 0).shape

torch.Size([1, 1, 2, 1, 2])

In [75]:
torch.unsqueeze(t,dim = 2).shape # 在第3个维度案引上升高1个维度

torch.Size([1, 2, 1, 1, 2])

In [76]:
torch.unsqueeze(t,dim = 4).shape # 在第5 个维度豪引上升高1个维度

torch.Size([1, 2, 1, 2, 1])